version: "3"
services:
  server:
    image: server:0.0.2
    ports:
      - "8080:8080"
    networks:
      - wnet
    volumes:
      - .:/app
    build: 
      .
    command: 
      python ./server.py

  prometheus:
    image: prom/prometheus:v2.40.7
    networks:
      - wnet
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.4.2
    ports:
      - "3000:3000"
    networks:
      - wnet
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    
    
networks:
   wnet: